[package]
edition = "2021"
name = "stronghold-nodejs"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
identity = { version = "=0.5.0-dev.4", path = "../../identity", default-features = false, features = ["account", "stronghold", "async"] }
futures = { version = "0.3" }
napi = { version = "2.0.3", default-features = false, features = ["napi4", "tokio_rt", "serde-json"] }
napi-derive = "2.0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
tokio = { version = "1.17", features = ["sync"] }

[build-dependencies]
napi-build = "1.2.1"

[profile.release]
lto = true
